services:
  - type: web
    name: numon-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
